INSERT INTO OWNER (full_name, email, phone_number) VALUES ('Saurabh Jindal', 'saurabhs@gmail.com', '9988772233');
INSERT INTO OWNER (full_name, email, phone_number) VALUES ('Arpit Sahoo', 'arpit.sahoo@gmail.com', '2429809232');
INSERT INTO OWNER (full_name, email, phone_number) VALUES ('Ranbir Agarwal', 'ranbir.agar@gmail.com', '4093494422');
INSERT INTO OWNER (full_name, email, phone_number) VALUES ('Rohit Singh', 'rohit.singh@gmail.com', '2909040933');
INSERT INTO OWNER (full_name, email, phone_number) VALUES ('Suman Verma', 'suman.verma@gmail.com', '8895859054');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, DATEADD('DAY', -1, CURRENT_DATE), '11:00', '12:00', 'Ankit Shah', 'ankit.shah@yahoo.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, DATEADD('DAY', -1, CURRENT_DATE), '16:00', '17:00', 'Rahul S', 'rahul.s@gmail.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, CURRENT_DATE, '10:00', '11:00', 'Shahrukh Khan', 'shahrukh.khan@yahoo.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, CURRENT_DATE, '17:00', '18:00', 'Astha Garg', 'astha.garg@yahoo.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, DATEADD('DAY', 1, CURRENT_DATE), '12:00', '13:00', 'Ankita Kapoor', 'ankita.kapoor@aol.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, DATEADD('DAY', 1, CURRENT_DATE), '13:00', '14:00', 'Jitu Kumar', 'jitu.k@rediffmail.com');
INSERT INTO APPOINTMENT (owner_id, date, start_time, end_time, invitee_name, invitee_email) VALUES (2, DATEADD('DAY', 2, CURRENT_DATE), '15:00', '16:00', 'Mahesh Tyagi', 'mahesh.tyagi@yahoo.com');
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'MONDAY', '10:00', '18:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'TUESDAY', '10:00', '18:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'WEDNESDAY', '10:00', '18:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'THURSDAY', '12:00', '18:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'FRIDAY', '01:00', '11:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'SATURDAY', '10:00', '18:00', false);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (2, 'SUNDAY', null, null, false);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (3, 'MONDAY', '10:00', '18:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (3, 'WEDNESDAY', '00:00', '23:00', true);
INSERT INTO AVAILABILITY_WEEKLY_RULE (owner_id, day_of_week, start_time, end_time, is_available) VALUES (3, 'SATURDAY', '00:00', '23:00', false);
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (2, DATEADD('DAY', -1, CURRENT_DATE), '12:00', '15:00',true, '');
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (2, DATEADD('DAY', 1, CURRENT_DATE), '12:00', '15:00',true, '');
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (2, DATEADD('WEEK', -1, CURRENT_DATE), '12:00', '15:00',true, '');
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (2, DATEADD('WEEK', 1, CURRENT_DATE), '00:00', '23:00',true, '');
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (3, DATEADD('DAY', 1, CURRENT_DATE), '12:00', '15:00',false, 'VACATION');
INSERT INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) values (3, DATEADD('DAY', 2, CURRENT_DATE), '12:00', '15:00',false, 'VACATION');
MERGE INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) KEY(owner_id, date) values (2, '2025-08-18', '10:00', '11:00',false, 'OFF SITE');
MERGE INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) KEY(owner_id, date) values (2, '2025-08-25', '12:00', '16:00',true, 'HALF DAY');
MERGE INTO AVAILABILITY_EXCEPTION_RULE (owner_id, date, start_time, end_time, is_available, description) KEY(owner_id, date) values (3, '2025-08-23', '11:00', '13:00',true, 'AVAILABLE');